'use client';
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import HeaderItem from "./components/HeaderItem";
import { useRouter } from 'next/navigation';

import { SearchProvider } from "./context/context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const { pathname } = router;

  const hideHeaderItems = ["/contact"];

  return (
    <html lang="en">
      <SearchProvider>
        <body
        style= {{background: "#1b2631"}}
        >
          <Navbar />
          <Header />
          {!hideHeaderItems.includes(pathname) && <HeaderItem />}
          {children}
        </body>
      </SearchProvider>
    </html>
  );
}

